.PHONY: all build test test-race test-multinode test-multinode-real lint verify

all: test

build:
	go build -o dezuxk main.go

test:
	go test -v -count=1 ./...

test-race:
	go test -race -v -count=1 ./...

test-multinode:
	go test -v -count=1 ./tests/multinode/...

test-multinode-real:
	bash scripts/test-multinode-cluster.sh

lint:
	go vet ./...
	staticcheck ./...
	govulncheck ./...

verify:
	go mod verify
	go vet ./...
	staticcheck ./...
	govulncheck ./...
	go test -v -count=1 ./...
